//
// Created by IgVelasco on 5/9/19.
//

#ifndef MARVEL_VS_CAPCOM_ORIENTATION_CONSTANTS_H
#define MARVEL_VS_CAPCOM_ORIENTATION_CONSTANTS_H


//TODO ADD MOVINGLEFT AND MOVINGRIGHT
#define S 0
#define JR 1
#define JL 2
#define JV 3
#define MI 4
#define D 5
#define ML 6
#define MR 7
#define WB 8
#define CM 9
#define CMO 10
#define DC 11
#define REC 12
#define AL 13
#define P 14
#define K 15
#define PD 16
#define KD 17
#define BL 18
#define HG 19
#define HA 20
#define THP 21
#define GR 22
#define FA 23
#define TH 24
#define PV 25
#define PJR 26
#define PJL 27
#define KV 28
#define KJR 29
#define KJL 30
#define PROJA 31
#define PROJD 32
#define PS 33
#define PSD 34
#define PSV 35
#define PSJR 36
#define PSJL 37
#define KS 38
#define KSD 39
#define KSV 40
#define KSJR 41
#define KSJL 42
#define SD 43




typedef enum actions {
    STANDING = S, JUMPINGLEFT = JL, JUMPINGRIGHT = JR, JUMPINGVERTICAL = JV, MAKINGINTRO = MI, DUCK = D,
    MOVINGRIGHT = MR, MOVINGLEFT = ML, WALKBACK = WB, CHANGEME = CM, CHANGEME_ONEPLAYER = CMO, DISCONNECTEDCLIENT = DC,
    RECONNECT = REC, ALIVE = AL, PUNCH = P, KICK = K, PUNCHDOWN = PD, KICKDOWN = KD, BLOCK = BL, HURTINGGROUND = HG,
    HURTINGAIR = HA, THROWPOWER =THP, GRIP = GR, FALLING = FA, THROW = TH, PUNCHINGVERTICAL = PV, PUNCHINGJUMPRIGHT = PJR, PUNCHINGJUMPLEFT = PJL,
    KICKINGVERTICAL = KV, KICKINGJUMPRIGHT = KJR, KICKINGJUMPLEFT = KJL, PROJECTILEALIVE = PROJA, PROJECTILEDEAD = PROJD,
	PUNCHSTRONG = PS, PUNCHSTRONGDOWN = PSD, PUNCHINGSTRONGVERTICAL = PSV, PUNCHINGSTRONGJUMPRIGHT = PSJR, PUNCHINGSTRONGJUMPLEFT = PSJL,
	KICKSTRONG = KS, KICKSTRONGDOWN = KSD, KICKINGSTRONGVERTICAL = KSV, KICKINGSTRONGJUMPRIGHT = KSJR, KICKINGSTRONGJUMPLEFT = KSJL,
	SWITCHDEBUG = SD

} actions_t;

typedef  enum round_action{
    NUMBEROFROUND = 200,
    ROUNDWINNER = 201,
    FIGHT = 202,
    FIGHTING = 203,

}round_action_t;

typedef enum music_action{
	HIT_MISS = 300,
	WEAK_PUNCH = 301,
	STRONG_PUNCH = 302,
	WEAK_KICK = 303,
	STRONG_KICK = 304,
	NEW_ROUND = 305,
	JUMP = 306,
	FALL = 307,
	THROWS = 308,
	PROJECTILE = 309,
	SPIDERINTRO = 400,
	WOLVERINTRO = 401,
	IRONINTRO = 402,
	RYUINTRO = 403,

}music_action_t;



typedef enum menuAction {
    SELECT = 94,
    MENU_WINDOWCLOSED = 95,
    RIGHT = 96,
    LEFT = 97,
    ENTER = 98,
    INVALID_MENU_ACTION = 99,
    ALIVE_MENU = 100,
    DISCONNECTED_MENU = 101,
    RECONNECTION_MENU = 102
} menu_action_t;


#endif //MARVEL_VS_CAPCOM_ORIENTATION_CONSTANTS_H
